services:

  backend-svc:
    container_name: backend-svc
    image: rupesh1997/backend:1.0.0
    ports:
      - "8181:8181"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8181/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    environment:
      SPRING_PROFILES_ACTIVE: default
    extends:
      file: common-config.yaml
      service: network-configuration

  frontend:
    container_name: frontend
    image: rupesh1997/frontend:1.0.0
    ports:
      - "4200:8080"
    restart: always
    depends_on:
      backend-svc:
        condition: service_started
    extends:
      file: common-config.yaml
      service: network-configuration

networks:
  devops:
    driver: bridge
