name: frontend pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'docker/frontend/Dockerfile'
      - '.github/workflows/frontend-pipeline.yaml'

# Prevents multiple pipelines from trying to commit to the repo at the same time
concurrency:
  group: gitops-updates
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.extract_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: extract_version
        run: echo "VERSION=$(jq -r '.version' frontend/package.json)" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET_KEY }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: docker/frontend/Dockerfile
          push: true
          platforms: linux/amd64
          # GHA Cache speeds up npm install / build layers
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.extract_version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          build-args: |
            CONFIGURATION=production

  update-deployments:
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Manifests
        env:
          VERSION: ${{ needs.build.outputs.VERSION }}
          USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          # 1. Update Docker Compose (Service Specific)
          yq -i ".services.frontend.image = \"$USER/frontend:$VERSION\"" docker/docker-compose/production/docker-compose.yaml
          
          # 2. Update Kubernetes (Targeted by container name) - containers:name
          sed -i "/name: frontend/,/image:/ s|image:.*|image: $USER/frontend:$VERSION|" kubernetes/frontend.yaml

      - name: Git Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          # Only commit if changes exist, then rebase to avoid conflicts
          git diff --staged --quiet || (git commit -m "chore: deploy frontend $VERSION [skip ci]" && git pull --rebase origin main && git push origin main)